-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintTest.

module PrintTest where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsTest

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsTest.Float where
  prt _ (AbsTest.Float i) = doc $ showString i
instance Print AbsTest.Id where
  prt _ (AbsTest.Id i) = doc $ showString i
instance Print AbsTest.Program where
  prt i = \case
    AbsTest.PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print [AbsTest.Def] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsTest.Def where
  prt i = \case
    AbsTest.DFun type_ id_ args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsTest.DFunInline type_ id_ args stms -> prPrec i 0 (concatD [doc (showString "inline"), prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsTest.QCDef qualconst -> prPrec i 0 (concatD [doc (showString "using"), prt 0 qualconst, doc (showString ";")])

instance Print [AbsTest.Arg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsTest.Arg where
  prt i = \case
    AbsTest.ADeclType type_ -> prPrec i 0 (concatD [prt 0 type_])
    AbsTest.ADeclId type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsTest.ADeclInit type_ id_ exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 exp])

instance Print AbsTest.Stm where
  prt i = \case
    AbsTest.SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    AbsTest.SWhi exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsTest.STDef type_ id_ -> prPrec i 0 (concatD [doc (showString "typedef"), prt 0 type_, prt 0 id_, doc (showString ";")])
    AbsTest.SBlo stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsTest.SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsTest.SIfE exp stm else_ -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm, prt 0 else_])
    AbsTest.SReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    AbsTest.SReturnVoid -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsTest.SVDecl type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString ";")])
    AbsTest.SVDecls type_ id_ ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString ","), prt 0 ids, doc (showString ";")])
    AbsTest.SVInits type_ id_ exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 exp, doc (showString ";")])

instance Print AbsTest.Else where
  prt i = \case
    AbsTest.SElIf exp stm else_ -> prPrec i 0 (concatD [doc (showString "elif"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm, prt 0 else_])
    AbsTest.SElse stm -> prPrec i 0 (concatD [doc (showString "else"), prt 0 stm])

instance Print [AbsTest.Stm] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsTest.Exp where
  prt i = \case
    AbsTest.ELit literal -> prPrec i 15 (concatD [prt 0 literal])
    AbsTest.EStrLit str exp -> prPrec i 15 (concatD [printString str, prt 15 exp])
    AbsTest.EQual qualconst -> prPrec i 15 (concatD [prt 0 qualconst])
    AbsTest.EIdx id_ exp -> prPrec i 14 (concatD [prt 0 id_, doc (showString "["), prt 0 exp, doc (showString "]")])
    AbsTest.EFun id_ exps -> prPrec i 14 (concatD [prt 0 id_, doc (showString "("), prt 0 exps, doc (showString ")")])
    AbsTest.EProD exp1 exp2 -> prPrec i 14 (concatD [prt 15 exp1, doc (showString "."), prt 14 exp2])
    AbsTest.EProA exp1 exp2 -> prPrec i 14 (concatD [prt 15 exp1, doc (showString "->"), prt 14 exp2])
    AbsTest.EMult exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    AbsTest.EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    AbsTest.ERem exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "%"), prt 13 exp2])
    AbsTest.EAdd exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    AbsTest.ESub exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    AbsTest.ENegInt n -> prPrec i 11 (concatD [doc (showString "-"), prt 0 n])
    AbsTest.EShiftR exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString ">>"), prt 11 exp2])
    AbsTest.EShiftL exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "<<"), prt 11 exp2])
    AbsTest.EEqu exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "=="), prt 9 exp2])
    AbsTest.EIneq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "!="), prt 9 exp2])
    AbsTest.EAsgn exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "="), prt 2 exp2])
    AbsTest.EAsgnAdd exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "+="), prt 2 exp2])
    AbsTest.EAsgnSub exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "-="), prt 2 exp2])
    AbsTest.ECond exp1 exp2 exp3 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "?"), prt 2 exp2, doc (showString ":"), prt 3 exp3])

instance Print [AbsTest.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsTest.QualConst where
  prt i = \case
    AbsTest.QualConstId id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsTest.QualConstRecId qualconst id_ -> prPrec i 0 (concatD [prt 0 qualconst, doc (showString "::"), prt 0 id_])
    AbsTest.QualConstTem qualconst templateinst -> prPrec i 0 (concatD [prt 0 qualconst, doc (showString "::"), prt 0 templateinst])

instance Print AbsTest.TemplateInst where
  prt i = \case
    AbsTest.TempInst id_ types -> prPrec i 0 (concatD [prt 0 id_, doc (showString "<"), prt 0 types, doc (showString ">")])

instance Print [AbsTest.Type] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsTest.Type where
  prt i = \case
    AbsTest.Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsTest.Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsTest.Type_char -> prPrec i 0 (concatD [doc (showString "char")])
    AbsTest.Type_double -> prPrec i 0 (concatD [doc (showString "double")])
    AbsTest.Type_void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsTest.TypeQualConst qualconst -> prPrec i 0 (concatD [prt 0 qualconst])
    AbsTest.Type1 type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&")])
    AbsTest.Type2 type_ -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_])

instance Print AbsTest.Literal where
  prt i = \case
    AbsTest.LiteralInteger n -> prPrec i 0 (concatD [prt 0 n])
    AbsTest.LiteralString str -> prPrec i 0 (concatD [printString str])
    AbsTest.LiteralChar c -> prPrec i 0 (concatD [prt 0 c])
    AbsTest.LiteralFloat float -> prPrec i 0 (concatD [prt 0 float])

instance Print [AbsTest.Id] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
